/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mike4
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    long clickcount = 0;
    long clickvalue = 1;
    long upgradecost = 10;
    long upgradecost2 = 125;
    long upgradecost3 = 10000;
    boolean upgrade3purchased = false;
    long upgradecost4 = 2500;
    
    Prestige prestige = new Prestige();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cookie = new javax.swing.JButton();
        CookieHolder = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Upgradecost = new javax.swing.JLabel();
        ClickValue = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Upgradecost2 = new javax.swing.JLabel();
        Upgrade3 = new javax.swing.JButton();
        Upgradecost3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Upgradecost4 = new javax.swing.JLabel();
        Upgrade4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Prestigelabel = new javax.swing.JLabel();
        Prestigemultiplier = new javax.swing.JLabel();
        Prestigerequirement = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Cookie.setIcon(new javax.swing.ImageIcon("C:\\Users\\mike4\\Downloads\\download__6_-removebg-preview.png")); // NOI18N
        Cookie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cookie.setBorderPainted(false);
        Cookie.setContentAreaFilled(false);
        Cookie.addActionListener(this::CookieActionPerformed);

        CookieHolder.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CookieHolder.setText("Cookies:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2026-01-08 165154.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel1.setText("Cursor Increase amount per click by +1");

        Upgradecost.setText("Upgrade Cost: 10");
        Upgradecost.addPropertyChangeListener(this::UpgradecostPropertyChange);

        ClickValue.setText("Click Value: 1");

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mike4\\OneDrive\\Pictures\\Screenshots 1\\Screenshot 2026-01-08 165341.png")); // NOI18N
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel2.setText("grandma Increases amount per click by +10");

        Upgradecost2.setText("Upgrade Cost: 125");

        Upgrade3.setIcon(new javax.swing.ImageIcon("C:\\Users\\mike4\\OneDrive\\Pictures\\Screenshots 1\\Screenshot 2026-01-08 170030.png")); // NOI18N
        Upgrade3.addActionListener(this::Upgrade3ActionPerformed);

        Upgradecost3.setText("Upgrade Cost: 10K");

        jLabel4.setText("farm Increases click value by 1.5x");

        Upgradecost4.setText("Upgrade Cost: 2,500");

        Upgrade4.setIcon(new javax.swing.ImageIcon("C:\\Users\\mike4\\OneDrive\\Pictures\\Screenshots 1\\Screenshot 2026-01-08 170333.png")); // NOI18N
        Upgrade4.setBorderPainted(false);
        Upgrade4.setContentAreaFilled(false);
        Upgrade4.addActionListener(this::Upgrade4ActionPerformed);

        jLabel5.setText("oven Increases click value by +100");

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Prestige");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        Prestigelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Prestigelabel.setText("Prestige: 0");

        Prestigemultiplier.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Prestigemultiplier.setText("Prestige Multiplier: 0");

        Prestigerequirement.setText("Prestige Requirement: 1.0M");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Upgradecost4)
                                    .addComponent(Upgradecost3))
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Prestigerequirement)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Prestigemultiplier)
                                            .addComponent(Prestigelabel))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Upgrade3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Upgrade4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cookie)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ClickValue)
                                .addGap(144, 144, 144))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CookieHolder)
                                .addGap(159, 159, 159)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Upgradecost2)
                            .addComponent(Upgradecost))
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Upgradecost)
                            .addComponent(ClickValue)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cookie, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Upgradecost2)
                                .addGap(74, 74, 74))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Upgradecost3)
                                .addGap(82, 82, 82)
                                .addComponent(Upgradecost4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CookieHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Prestigerequirement))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Upgrade3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Upgrade4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Prestigemultiplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Prestigelabel)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String formatNumber(long num) {
    if (num >= 1_000_000_000) {
        return String.format("%.1fB", num / 1_000_000_000.0);
    } else if (num >= 1_000_000) {
        return String.format("%.1fM", num / 1_000_000.0);
    } else if (num >= 1_000) {
        return String.format("%.1fK", num / 1_000.0);
    } else {
        return String.valueOf(num);
    }
}
    public double getUpgrade3Potential(long cookies) {
    return 1 + Math.log10(cookies + 1);
}

    private void CookieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CookieActionPerformed
        // TODO add your handling code here:
    clickcount += (int)(clickvalue*prestige.prestigemultiplier);
    CookieHolder.setText("Cookies: " + formatNumber(clickcount));
    double potential = getUpgrade3Potential(clickcount); jLabel4.setText("Potential: x" + String.format("%.2f", potential));
    }//GEN-LAST:event_CookieActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    if (clickcount >= upgradecost) {
        clickcount -= upgradecost;
        clickvalue++;
        upgradecost += 10;
        CookieHolder.setText("Cookies: " + formatNumber(clickcount));
        Upgradecost.setText("Upgrade Cost: " + formatNumber(upgradecost));
        ClickValue.setText("Click Value: " + formatNumber(clickvalue));
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UpgradecostPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_UpgradecostPropertyChange
        // TODO add your handling code here:
     
    }//GEN-LAST:event_UpgradecostPropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (clickcount >= upgradecost2) {
            clickcount -= upgradecost2;
            clickvalue += 10;
            upgradecost2 += 75;
            CookieHolder.setText("Cookies: " + formatNumber(clickcount));
            Upgradecost2.setText("Upgrade cost: " + formatNumber(upgradecost2));
            ClickValue.setText("Click Value: " + formatNumber(clickvalue));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Upgrade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Upgrade3ActionPerformed
        // TODO add your handling code here:
       if (clickcount >= upgradecost3 && !upgrade3purchased) {
           clickcount -= upgradecost3;
           double scale = getUpgrade3Potential(clickcount);
           clickvalue *= scale;
           upgrade3purchased = true; 
           CookieHolder.setText("Cookies: " + formatNumber(clickcount));
           Upgradecost3.setText("Purchased!");
           ClickValue.setText("Click Value: " + formatNumber(clickvalue));
       }
    }//GEN-LAST:event_Upgrade3ActionPerformed

    private void Upgrade4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Upgrade4ActionPerformed
        // TODO add your handling code here:
       if (clickcount >= upgradecost4) {
           clickcount -= upgradecost4;
           clickvalue += 100;
           upgradecost4 += 1500;
           CookieHolder.setText("Cookies: " + formatNumber(clickcount));
           Upgradecost4.setText("Upgrade cost: " + formatNumber(upgradecost4));
           ClickValue.setText("Click Value: " + formatNumber(clickvalue));
       }
    }//GEN-LAST:event_Upgrade4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (prestige.canPrestige(clickcount)) {
            prestige.applyPrestige();           
            
            clickcount = 0; 
            clickvalue = 1;
            upgradecost = 10;
            Upgradecost.setText("Upgrade Cost: " + upgradecost);
            upgradecost2 = 125;
            Upgradecost2.setText("Upgrade Cost: " + upgradecost2);
            upgradecost3 = 10000;
            Upgradecost3.setText("Upgrade Cost: " + upgradecost3);
            upgradecost4 = 2500;
            Upgradecost4.setText("Upgrade Cost: " + upgradecost4);
            upgrade3purchased = false;
           
            Prestigerequirement.setText("Prestige Cost: " + formatNumber(prestige.prestigerequirement));
            CookieHolder.setText("Cookies: " + clickcount);
            Prestigelabel.setText("Prestige: " + formatNumber(prestige.prestigepoints));
            Prestigemultiplier.setText("Multiplier: x" + prestige.prestigemultiplier);
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClickValue;
    private javax.swing.JButton Cookie;
    private javax.swing.JLabel CookieHolder;
    private javax.swing.JLabel Prestigelabel;
    private javax.swing.JLabel Prestigemultiplier;
    private javax.swing.JLabel Prestigerequirement;
    private javax.swing.JButton Upgrade3;
    private javax.swing.JButton Upgrade4;
    private javax.swing.JLabel Upgradecost;
    private javax.swing.JLabel Upgradecost2;
    private javax.swing.JLabel Upgradecost3;
    private javax.swing.JLabel Upgradecost4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
