/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.prefs.Preferences;
/**
 *
 * @author mike4
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        new javax.swing.Timer(1000, e -> {
    clickcount += passiveclicks * prestige.prestigemultiplier;
    CookieHolder.setText("Cookies: " + formatNumber(clickcount));
    jLabel8.setText("Passive Cookies/sec: " + formatNumber(passiveclicks));
}).start();

    }
    long clickcount = 0;
    long clickvalue = 1;
    long upgradecost = 10;
    long upgradecost2 = 125;
    long upgradecost3 = 10000;
    boolean upgrade3purchased = false;
    long upgradecost4 = 2500;
    long upgradecost5 = 5000;
    long passiveclicks = 0;
    
    Prestige prestige = new Prestige();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cookie = new javax.swing.JButton();
        CookieHolder = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Upgradecost = new javax.swing.JLabel();
        ClickValue = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Upgradecost2 = new javax.swing.JLabel();
        Upgrade3 = new javax.swing.JButton();
        Upgradecost3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Upgradecost4 = new javax.swing.JLabel();
        Upgrade4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Prestigelabel = new javax.swing.JLabel();
        Prestigemultiplier = new javax.swing.JLabel();
        Prestigerequirement = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SAVE = new javax.swing.JButton();
        LOAD = new javax.swing.JButton();
        passiveclicks1 = new javax.swing.JButton();
        Upgradecost5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Cookie.setIcon(new javax.swing.ImageIcon("C:\\Users\\mike4\\Downloads\\download__6_-removebg-preview.png")); // NOI18N
        Cookie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cookie.setBorderPainted(false);
        Cookie.setContentAreaFilled(false);
        Cookie.addActionListener(this::CookieActionPerformed);

        CookieHolder.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CookieHolder.setText("Cookies:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2026-01-08 165154.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel1.setText("Cursor Increase amount per click by +1");

        Upgradecost.setText("Upgrade Cost: 10");
        Upgradecost.addPropertyChangeListener(this::UpgradecostPropertyChange);

        ClickValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ClickValue.setText("Click Value: 1");

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mike4\\OneDrive\\Pictures\\Screenshots 1\\Screenshot 2026-01-08 165341.png")); // NOI18N
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel2.setText("grandma Increases amount per click by +10");

        Upgradecost2.setText("Upgrade Cost: 125");

        Upgrade3.setIcon(new javax.swing.ImageIcon("C:\\Users\\mike4\\OneDrive\\Pictures\\Screenshots 1\\Screenshot 2026-01-08 170030.png")); // NOI18N
        Upgrade3.addActionListener(this::Upgrade3ActionPerformed);

        Upgradecost3.setText("Upgrade Cost: 10K");

        jLabel4.setText("farm Increases click value by 1.5x");

        Upgradecost4.setText("Upgrade Cost: 2.5K");

        Upgrade4.setIcon(new javax.swing.ImageIcon("C:\\Users\\mike4\\OneDrive\\Pictures\\Screenshots 1\\Screenshot 2026-01-08 170333.png")); // NOI18N
        Upgrade4.setBorderPainted(false);
        Upgrade4.setContentAreaFilled(false);
        Upgrade4.addActionListener(this::Upgrade4ActionPerformed);

        jLabel5.setText("oven Increases click value by +100");

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Prestige");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        Prestigelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Prestigelabel.setText("Prestige: 0");

        Prestigemultiplier.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Prestigemultiplier.setText("Prestige Multiplier: 0");

        Prestigerequirement.setText("Prestige Requirement: 1.0M");

        SAVE.setText("SAVE");
        SAVE.addActionListener(this::SAVEActionPerformed);

        LOAD.setText("LOAD");
        LOAD.addActionListener(this::LOADActionPerformed);

        passiveclicks1.setText("Passive Clicks");
        passiveclicks1.addActionListener(this::passiveclicks1ActionPerformed);

        Upgradecost5.setText("Upgrade Cost: 5k");

        jLabel7.setText("Increases passive clicks by 5/Sec");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Passive Cookies/sec:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SAVE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(Prestigerequirement)
                                    .addComponent(Prestigemultiplier)
                                    .addComponent(Prestigelabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cookie)
                                    .addComponent(ClickValue)
                                    .addComponent(jLabel8))
                                .addGap(222, 222, 222)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(LOAD)
                                .addGap(116, 116, 116))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Upgradecost3)
                                            .addComponent(Upgradecost2)
                                            .addComponent(Upgradecost))
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Upgrade3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Upgradecost4)
                                            .addComponent(Upgradecost5))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Upgrade4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(passiveclicks1, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(7, 7, 7))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(CookieHolder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ClickValue)
                        .addGap(18, 18, 18)
                        .addComponent(Cookie, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Upgradecost)
                                .addGap(76, 76, 76)
                                .addComponent(Upgradecost2)
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Upgrade3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(Upgrade4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Upgradecost3)
                                        .addGap(116, 116, 116)
                                        .addComponent(Upgradecost4)
                                        .addGap(50, 50, 50))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(31, 31, 31)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(262, 262, 262))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(87, 87, 87)
                                .addComponent(jLabel2)
                                .addGap(114, 114, 114)
                                .addComponent(jLabel4)
                                .addGap(111, 111, 111)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Prestigerequirement)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Prestigemultiplier)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Prestigelabel)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CookieHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passiveclicks1)
                    .addComponent(Upgradecost5)
                    .addComponent(jLabel7))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SAVE)
                    .addComponent(LOAD))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Preferences save = Preferences.userRoot().node("CookieClickerSave");
    public String formatNumber(long num) {
    if (num >= 1_000_000_000) {
        return String.format("%.1fB", num / 1_000_000_000.0);
    } else if (num >= 1_000_000) {
        return String.format("%.1fM", num / 1_000_000.0);
    } else if (num >= 1_000) {
        return String.format("%.1fK", num / 1_000.0);
    } else {
        return String.valueOf(num);
    }
}
    public double getUpgrade3Potential(long cookies) {
    return 1 + Math.log10(cookies + 1);
}
    public void savegame() {
        save.putLong("Cookies", clickcount);
        save.putLong("Click Value", clickvalue);
        save.putLong("Prestige", prestige.prestigepoints);
        save.putLong("Prestige Requirement", prestige.prestigerequirement);
        save.putDouble("Prestige Multiplier", prestige.prestigemultiplier);
        save.putLong("Passive Clicks", passiveclicks);
        save.putLong("Upgrade Cost", upgradecost5);
    }
    public void loadgame() {
        clickcount = save.getLong("Cookies", 0);
        clickvalue = save.getLong("Click Value", 1);
        prestige.prestigepoints = save.getLong("Prestige", 0);
        prestige.prestigerequirement = save.getLong("Prestige Requirement", 1_000_000);
        prestige.prestigemultiplier = save.getDouble("Prestige Multiplier", 1.0);
        passiveclicks = save.getLong("Passive Clicks", 0);
        upgradecost5 = save.getLong("Upgrade Cost", 5000);
        
        jLabel8.setText("Passive Cookies/sec " + formatNumber(passiveclicks));
        CookieHolder.setText("Cookies: " + formatNumber(clickcount)); 
        ClickValue.setText("Click Value: " + formatNumber(clickvalue)); 
        Prestigelabel.setText("Prestige: " + formatNumber(prestige.prestigepoints)); 
        Prestigemultiplier.setText("Multiplier: " + prestige.prestigemultiplier); 
        Prestigerequirement.setText("Prestige Requirement: " + formatNumber(prestige.prestigerequirement));
    }
    private void CookieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CookieActionPerformed
        // TODO add your handling code here:
    clickcount += (int)(clickvalue*prestige.prestigemultiplier);
    CookieHolder.setText("Cookies: " + formatNumber(clickcount));
    double potential = getUpgrade3Potential(clickcount); jLabel4.setText("Potential: x" + String.format("%.2f", potential));
    }//GEN-LAST:event_CookieActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    if (clickcount >= upgradecost) {
        clickcount -= upgradecost;
        clickvalue++;
        upgradecost += 10;
        CookieHolder.setText("Cookies: " + formatNumber(clickcount));
        Upgradecost.setText("Upgrade Cost: " + formatNumber(upgradecost));
        ClickValue.setText("Click Value: " + formatNumber(clickvalue));
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UpgradecostPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_UpgradecostPropertyChange
        // TODO add your handling code here:
     
    }//GEN-LAST:event_UpgradecostPropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (clickcount >= upgradecost2) {
            clickcount -= upgradecost2;
            clickvalue += 10;
            upgradecost2 += 75;
            CookieHolder.setText("Cookies: " + formatNumber(clickcount));
            Upgradecost2.setText("Upgrade cost: " + formatNumber(upgradecost2));
            ClickValue.setText("Click Value: " + formatNumber(clickvalue));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Upgrade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Upgrade3ActionPerformed
        // TODO add your handling code here:
       if (clickcount >= upgradecost3 && !upgrade3purchased) {
           clickcount -= upgradecost3;
           double scale = getUpgrade3Potential(clickcount);
           clickvalue *= scale;
           upgrade3purchased = true; 
           CookieHolder.setText("Cookies: " + formatNumber(clickcount));
           Upgradecost3.setText("Purchased!");
           ClickValue.setText("Click Value: " + formatNumber(clickvalue));
       }
    }//GEN-LAST:event_Upgrade3ActionPerformed

    private void Upgrade4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Upgrade4ActionPerformed
        // TODO add your handling code here:
       if (clickcount >= upgradecost4) {
           clickcount -= upgradecost4;
           clickvalue += 100;
           upgradecost4 += 1500;
           CookieHolder.setText("Cookies: " + formatNumber(clickcount));
           Upgradecost4.setText("Upgrade cost: " + formatNumber(upgradecost4));
           ClickValue.setText("Click Value: " + formatNumber(clickvalue));
       }
    }//GEN-LAST:event_Upgrade4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (prestige.canPrestige(clickcount)) {
            prestige.applyPrestige();           
            
            double scale = 1 + (prestige.prestigepoints * 0.25); 
            clickcount = 0; 
            clickvalue = 1;
            upgrade3purchased = false;
            passiveclicks = 0;
            
            upgradecost = (long)(10 * scale); 
            upgradecost2 = (long)(125 * scale); 
            upgradecost3 = (long)(10000 * scale); 
            upgradecost4 = (long)(2500 * scale); 
            upgradecost5 = (long)(5000 * scale);
            
            Upgradecost.setText("Upgrade Cost: " + formatNumber(upgradecost));
            Upgradecost2.setText("Upgrade Cost: " + formatNumber(upgradecost2));
            Upgradecost3.setText("Upgrade Cost: 10K"); 
            Upgradecost4.setText("Upgrade Cost: " + formatNumber(upgradecost4));
            Upgradecost5.setText("Upgrade Cost: " + formatNumber(upgradecost5));
           
            Prestigerequirement.setText("Prestige Cost: " + formatNumber(prestige.prestigerequirement));
            CookieHolder.setText("Cookies: " + clickcount);
            Prestigelabel.setText("Prestige: " + formatNumber(prestige.prestigepoints));
            Prestigemultiplier.setText("Multiplier: x" + prestige.prestigemultiplier);
            jLabel8.setText("Passive Cookies/sec: 0"); 
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        savegame();
    }//GEN-LAST:event_SAVEActionPerformed

    private void LOADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOADActionPerformed
        loadgame();
    }//GEN-LAST:event_LOADActionPerformed

    private void passiveclicks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passiveclicks1ActionPerformed
        if (clickcount >= upgradecost5) {
            clickcount -= upgradecost5;
            passiveclicks += 5; 
            upgradecost5 *= 1.15;
            
            jLabel8.setText("Passive Cookies/sec: " + formatNumber(passiveclicks));
            Upgradecost5.setText("Upgrade Cost: " + formatNumber(upgradecost5));
        }
    }//GEN-LAST:event_passiveclicks1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClickValue;
    private javax.swing.JButton Cookie;
    private javax.swing.JLabel CookieHolder;
    private javax.swing.JButton LOAD;
    private javax.swing.JLabel Prestigelabel;
    private javax.swing.JLabel Prestigemultiplier;
    private javax.swing.JLabel Prestigerequirement;
    private javax.swing.JButton SAVE;
    private javax.swing.JButton Upgrade3;
    private javax.swing.JButton Upgrade4;
    private javax.swing.JLabel Upgradecost;
    private javax.swing.JLabel Upgradecost2;
    private javax.swing.JLabel Upgradecost3;
    private javax.swing.JLabel Upgradecost4;
    private javax.swing.JLabel Upgradecost5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton passiveclicks1;
    // End of variables declaration//GEN-END:variables
}
